# Generated by Django 5.1.1 on 2024-09-29 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nom_completo_pac', models.CharField(max_length=100)),
                ('informe', models.CharField(max_length=300)),
                ('fecha_nac', models.DateField()),
                ('genero', models.CharField(max_length=100)),
                ('huella_dactilar', models.ImageField(upload_to='huellas_dactilares/')),
                ('email', models.EmailField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PacienteServicio',
            fields=[
                ('id_paciente_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id_doctor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('area_desempeño', models.CharField(max_length=100)),
                ('fec_nac', models.DateField()),
                ('num_telefono', models.CharField(max_length=100)),
                ('sitio_id_sitio', models.IntegerField()),
            ],
            options={
                'unique_together': {('id_doctor', 'sitio_id_sitio')},
            },
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id_informe', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo_pac', models.CharField(max_length=200)),
                ('tipo_servicio', models.TextField()),
                ('medico_designado', models.CharField(max_length=100)),
                ('resultados_pac', models.TextField()),
                ('tratamiento', models.CharField(max_length=300)),
                ('foto_pac', models.ImageField(upload_to='fotos_pacientes/')),
                ('archivo_informe', models.ImageField(upload_to='archivos_informes/')),
                ('doctor_id_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes', to='consultorioCys.doctor')),
            ],
        ),
    ]
