# Generated by Django 5.1.1 on 2024-10-16 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id_clinica', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_clinica', models.CharField(max_length=100)),
                ('correo_clinica', models.EmailField(max_length=100)),
                ('telefono_clinica', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Clínica',
                'verbose_name_plural': 'Clínicas',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('rut_doctor', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombres_doctor', models.CharField(max_length=100)),
                ('primer_apellido_doctor', models.CharField(max_length=50)),
                ('segundo_apellido_doctor', models.CharField(max_length=50)),
                ('correo_doctor', models.EmailField(max_length=100)),
                ('telefono_doctor', models.CharField(max_length=15)),
                ('fecha_nacimiento_doctor', models.DateField(blank=True, null=True)),
                ('especialidad_doctor', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('rut_paciente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombres_paciente', models.CharField(max_length=100)),
                ('primer_apellido_paciente', models.CharField(max_length=50)),
                ('segundo_apellido_paciente', models.CharField(blank=True, max_length=50)),
                ('correo_paciente', models.EmailField(max_length=100)),
                ('telefono_paciente', models.CharField(max_length=15)),
                ('fecha_nacimiento_paciente', models.DateField(blank=True, null=True)),
                ('direccion_paciente', models.CharField(blank=True, max_length=100)),
                ('genero_paciente', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-binary')], max_length=2)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id_informe', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_informe', models.CharField(max_length=200)),
                ('descripcion_informe', models.TextField(default='Descripción por defecto.')),
                ('notas_doctor', models.TextField(blank=True)),
                ('instrucciones_tratamiento', models.TextField(blank=True)),
                ('fecha_informe', models.DateTimeField(auto_now_add=True)),
                ('documentos_extra', models.FileField(blank=True, upload_to='documentos_extra/')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorioCys.doctor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorioCys.paciente')),
            ],
            options={
                'verbose_name': 'Informe',
                'verbose_name_plural': 'Informes',
            },
        ),
        migrations.CreateModel(
            name='PacienteInforme',
            fields=[
                ('id_paciente_informe', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorioCys.informe')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorioCys.paciente')),
            ],
            options={
                'verbose_name': 'Paciente Informe',
                'verbose_name_plural': 'Informes de Pacientes',
            },
        ),
        migrations.CreateModel(
            name='SedeClinica',
            fields=[
                ('id_sede', models.AutoField(primary_key=True, serialize=False)),
                ('region_sede', models.CharField(max_length=30)),
                ('comuna_sede', models.CharField(max_length=30)),
                ('direccion_sede', models.CharField(max_length=100)),
                ('telefono_sede', models.CharField(max_length=15)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorioCys.clinica')),
            ],
            options={
                'verbose_name': 'Sede Clínica',
                'verbose_name_plural': 'Sedes Clínicas',
            },
        ),
        migrations.CreateModel(
            name='DoctorClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorioCys.clinica')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorioCys.doctor')),
            ],
            options={
                'verbose_name': 'Doctor en Clínica',
                'verbose_name_plural': 'Doctores en Clínicas',
                'unique_together': {('doctor', 'clinica')},
            },
        ),
    ]
