# Generated by Django 5.1.1 on 2024-10-16 19:43

from django.db import migrations

def create_initial_data(apps, schema_editor):
    Doctor = apps.get_model('consultorioCys', 'Doctor')
    Paciente = apps.get_model('consultorioCys', 'Paciente')

    # Eliminar registros existentes
    Doctor.objects.filter(rut_doctor="1234567890").delete()
    Doctor.objects.filter(rut_doctor="0987654321").delete()

    # Insertar nuevos datos
    Doctor.objects.create(
        rut_doctor="1234567890",
        nombres_doctor="Juan Carlos",
        primer_apellido_doctor="García",
        segundo_apellido_doctor="Martínez",
        correo_doctor="juancarlos.garcia@example.com",
        telefono_doctor="555-1234",
        fecha_nacimiento_doctor="1975-06-15",
        especialidad_doctor="Cardiología"
    )
    Doctor.objects.create(
        rut_doctor="0987654321",
        nombres_doctor="Ana María",
        primer_apellido_doctor="López",
        segundo_apellido_doctor="Rodríguez",
        correo_doctor="anamaria.lopez@example.com",
        telefono_doctor="555-5678",
        fecha_nacimiento_doctor="1980-11-25",
        especialidad_doctor="Pediatría"
    )

    # Insertar pacientes como ejemplo
    Paciente.objects.create(
        rut_paciente="1234567890",
        nombres_paciente="Pedro José",
        primer_apellido_paciente="Fernández",
        segundo_apellido_paciente="Gómez",
        correo_paciente="pedro.fernandez@example.com",
        telefono_paciente="555-9876",
        fecha_nacimiento_paciente="1990-08-10"
    )
    Paciente.objects.create(
        rut_paciente="0987654321",
        nombres_paciente="María Fernanda",
        primer_apellido_paciente="Ramírez",
        segundo_apellido_paciente="Sánchez",
        correo_paciente="maria.ramirez@example.com",
        telefono_paciente="555-4321",
        fecha_nacimiento_paciente="1995-04-22"
    )
    Doctor.objects.get_or_create(
    rut_doctor="1234567890",
    defaults={
        "nombres_doctor": "Juan Carlos",
        "primer_apellido_doctor": "García",
        "segundo_apellido_doctor": "Martínez",
        "correo_doctor": "juancarlos.garcia@example.com",
        "telefono_doctor": "555-1234",
        "fecha_nacimiento_doctor": "1975-06-15",
        "especialidad_doctor": "Cardiología"
    }
)



class Migration(migrations.Migration):

    dependencies = [
        ('consultorioCys', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]
