# Generated by Django 5.1.1 on 2024-10-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorioCys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos_pacientes/'),
        ),
    ]
