# Generated by Django 5.1.1 on 2024-10-10 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorioCys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('id_sitio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sitio', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='informe',
            old_name='doctor_id_doctor',
            new_name='doctor',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='informe',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='num_telefono',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='informe',
            name='archivo_informe',
            field=models.FileField(upload_to='archivos_informes/'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='doctor',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='doctor',
            name='sitio',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='consultorioCys.sitio'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='doctor',
            unique_together={('id_doctor', 'sitio')},
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='sitio_id_sitio',
        ),
    ]
