# Generated by Django 5.1.1 on 2024-10-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorioCys', '0002_auto_20241016_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='contrasena_doctor',
            field=models.CharField(default='12345678', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='contrasena_paciente',
            field=models.CharField(default='12345678', max_length=128),
            preserve_default=False,
        ),
    ]
