# Generated by Django 5.1.1 on 2024-12-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorioCys', '0002_alter_informe_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
